app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/**
 * Website Routes
 */

# 404
Route::get('/404', ['as' => '404', 'uses' => function() {
    return View::make('website.pages.404');
}]);

# Pages
Route::get('/', ['as' => 'home', 'uses' => 'HomeController@getIndex']);
Route::get('roadmap', ['as' => 'pages.roadmap', 'uses' => 'Website\PagesController@showRoadmap']);

# Signup
Route::get('signup', ['as' => 'auth.getSignup', 'uses' => 'AuthController@getSignup']);
Route::post('signup', ['before' => 'csrf', 'as' => 'auth.postSignup', 'uses' => 'AuthController@postSignup']);

# Login
Route::get('login', ['as' => 'auth.getLogin', 'uses' => 'AuthController@getLogin']);
Route::post('login', ['before' => 'csrf', 'as' => 'auth.postLogin', 'uses' => 'AuthController@postLogin']);

# Logout
Route::get('logout', ['as' => 'auth.getLogout', 'uses' => 'AuthController@getLogout']);
Route::get('auth/activate/{userSlug}/key/{activationKey}', ['as' => 'auth.getActivateAccount', 'uses' => 'AuthController@getActivateAccount']);

/**
 * Snippet Routes
 */
Route::get('snippets', ['as' => 'snippet.getIndex', 'uses' => 'SnippetController@getIndex']);
Route::get('snippets/{slug}', ['as' => 'snippet.getShow', 'uses' => 'SnippetController@getShow']);
Route::get('snippets/{slug}/star', ['as' => 'snippet.star', 'uses' => 'SnippetController@starSnippet']);
Route::get('snippets/{slug}/unstar', ['as' => 'snippet.unStar', 'uses' => 'SnippetController@unstarSnippet']);

/**
 * Tag Routes
 */
Route::get('tags/{slug}', ['as' => 'tag.getShow', 'uses' => 'TagController@getShow']);

/**
 * Password Reset Routes
 */
Route::get('password/remind', ['as' => 'password.remind', 'uses' => 'RemindersController@getRemind']);
Route::post('password/remind', ['before' => 'csrf', 'as' => 'password.remind', 'uses' => 'RemindersController@postRemind']);
Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'RemindersController@getReset']);
Route::post('password/reset/{token}', ['before' => 'csrf', 'as' => 'password.reset', 'uses' => 'RemindersController@postReset']);

/**
 * Profile Routes
 */
Route::get('profiles', ['as' => 'user.getIndex', 'uses' => 'UserController@getIndex']);
Route::get('profiles/{slug}', ['as' => 'user.getProfile', 'uses' => 'UserController@getProfile']);
Route::get('profiles/{slug}/settings', ['as' => 'user.getSettings', 'uses' => 'UserController@getSettings']);
Route::put('profiles/{slug}/settings', ['as' => 'user.putSettings', 'uses' => 'UserController@putSettings']);
Route::get('profiles/{slug}/snippets', ['as' => 'user.getSnippets', 'uses' => 'UserController@getSnippets']);

/**
 * Member Routes
 */
Route::group(
    ['prefix' => 'members', 'before' => ['auth']],
    function () {

        # Dashboard
        Route::get('dashboard', ['as' => 'member.user.dashboard', 'uses' => 'Member\UserController@dashboard']);

        # Snippets
        Route::get('snippets/{slug}', ['as' => 'member.snippet.getShow', 'uses' => 'Member\SnippetController@getShow']);
        Route::get('snippets/{slug}/edit', ['as' => 'member.snippet.getEdit', 'uses' => 'Member\SnippetController@getEdit']);
        Route::post('snippets/{slug}/update', ['before' => 'csrf', 'as' => 'member.snippet.postUpdate', 'uses' => 'Member\SnippetController@postUpdate']);
        Route::get('submit/snippet', ['as' => 'member.snippet.getCreate', 'uses' => 'Member\SnippetController@getCreate']);
        Route::post('submit/snippet', ['before' => 'csrf', 'as' => 'member.snippet.postStore', 'uses' => 'Member\SnippetController@postStore']);

    });

/**
 * Admin Routes
 */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/', ['as' => 'admin.index', 'uses' => 'IndexController@getIndex']);
});

app/models/User.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends BaseModel implements UserInterface, RemindableInterface
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The fields who are mass assignable
     *
     * @var string
     */
    protected $fillable = array(
        'username',
        'password',
        'first_name',
        'last_name',
        'email',
        'twitter_url',
        'github_url',
        'facebook_url',
        'website_url',
        'about_me'
    );

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array('password');

    /**
     * Config for eloquent sluggable package
     * Reference: https://github.com/cviebrock/eloquent-sluggable
     *
     * @var array
     */
    public static $sluggable = array(
        'build_from' => 'full_name',
        'save_to' => 'slug',
    );

    /**
     * Define a one-to-many relationship.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function snippets()
    {
        return $this->hasMany('Snippet', 'author_id');
    }

    /**
     * A user has a role, like administration etc.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role()
    {
        return $this->belongsTo('Role');
    }

    /**
     * The user has starred snippets
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function starred()
    {
        return $this->hasMany('Starred');
    }

    /**
     * Get the unique identifier for the user.
     *
     * @return mixed
     */
    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Get the password for the user.
     *
     * @return string
     */
    public function getAuthPassword()
    {
        return $this->password;
    }

    /**
     * Get the token value for the "remember me" session.
     *
     * @return string
     */
    public function getRememberToken()
    {
        return $this->remember_token;
    }

    /**
     * Set the token value for the "remember me" session.
     *
     * @param  string $value
     * @return void
     */
    public function setRememberToken($value)
    {
        $this->remember_token = $value;
    }

    /**
     * Get the column name for the "remember me" token.
     *
     * @return string
     */
    public function getRememberTokenName()
    {
        return 'remember_token';
    }

    /**
     * Get the e-mail address where password reminders are sent.
     *
     * @return string
     */
    public function getReminderEmail()
    {
        return $this->email;
    }

    /**
     * Full name eloquent accessor
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    /**
     * Returns the absolute url for the profile picture
     * @return string
     */
    public function getAbsPhotoUrlAttribute()
    {
        if (!$this->photo_url) {

            $hash = md5(trim(strtolower($this->attributes["email"])));

            return "http://www.gravatar.com/avatar/" . $hash . "?s=120";
        }

        $assetsDir = asset('/');

        return $assetsDir . $this->photo_url;
    }

    /**
     * Gets the number of snippets that a user has
     * @return mixed
     */
    public function getSnippetsCountAttribute()
    {
        return $this->snippets()->where('approved', 1)->count();
    }

    /**
     * Password eloquent mutator
     *
     * @param $value
     * @return string
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    /**
     * Checks if user is active
     *
     * @return boolean
     */
    public function isActive()
    {
        return $this->active ? true : false;
    }

    /**
     * Activates a user
     *
     * @param $key
     * @throws RuntimeException
     * @return boolean
     */
    public function activate($key)
    {
        if ($this->activation_key === $key) {

            $this->active = 1;

            if ($this->save()) {
                return true;
            }

            throw new \RuntimeException('Saving to database failed.');
        }

        return false;
    }

    /**
     * Checks if user is administration
     *
     * @return boolean
     */
    public function isAdmin()
    {
        return $this->role->name === 'admin';
    }

    /**
     * Checks if a user has starred a snippet
     *
     * @param  integer $snippet_id
     * @return bool
     */
    public function hasStarred($snippet_id)
    {
        return $this->starred()->whereSnippetId($snippet_id)->count() ? true : false;
    }

    /**
     * Stars a snippet
     *
     * @param  integer $snippet_id
     * @return bool
     */
    public function starSnippet($snippet_id)
    {
        if ($this->hasStarred($snippet_id)) {
            return;
        }

        $this->starred()->create(array('snippet_id' => $snippet_id));
    }

    /**
     * Unstars a snippet
     *
     * @param  integer $snippet_id
     * @return bool
     */
    public function unstarSnippet($snippet_id)
    {
        if (!$this->hasStarred($snippet_id)) {
            return;
        }

        $this->starred()->whereSnippetId($snippet_id)->delete();
    }

}

app/controllers/Member/UserController.php
<?php namespace Member;

use BaseController;
use View;
use Input;
use Paginator;
use Auth;
use LaraSnipp\Repo\Snippet\SnippetRepositoryInterface;

class UserController extends BaseController
{
    /**
     * Snippet repository
     *
     * @var \LaraSnipp\Repo\Snippet\SnippetRepositoryInterface
     */
    protected $snippet;

    public function __construct(SnippetRepositoryInterface $snippet)
    {
        $this->snippet = $snippet;
    }

    /**
     * Show dashboard with snippets and starred snippets of the current logged-in user
     * GET /members/dashboard
     */
    public function dashboard()
    {
        $page = Input::get('page', 1);

        // Candidate for config item
        $perPage = 10;

        $pagiData = $this->snippet->byAuthor(Auth::user()->slug, $page, $perPage, $all = true);
        $my_snippets = Paginator::make($pagiData->items, $pagiData->totalItems, $perPage);

        $user = Auth::user();
        $starred_snippets = $user->starred()->with('Snippet')->get();

        return View::make('member.users.dashboard', compact('my_snippets', 'starred_snippets'));
    }
}

app/controllers/UserController.php
<?php

use Illuminate\Support\Facades\Redirect;
use LaraSnipp\Repo\Snippet\SnippetRepositoryInterface;
use LaraSnipp\Repo\User\UserRepositoryInterface;
use LaraSnipp\Service\Form\User\UserForm;

class UserController extends BaseController
{
    /**
     * Snippet repository
     *
     * @var \LaraSnipp\Repo\Snippet\SnippetRepositoryInterface
     */
    protected $snippet;

    /**
     * User repository
     *
     * @var \LaraSnipp\Repo\Snippet\UserRepositoryInterface
     */
    protected $user;
    /**
     * @var UserForm
     */
    private $userForm;

    /**
     * @param UserRepositoryInterface $user
     * @param SnippetRepositoryInterface $snippet
     * @param UserForm $userForm
     */
    public function __construct(UserRepositoryInterface $user, SnippetRepositoryInterface $snippet, UserForm $userForm)
    {
        $this->user = $user;
        $this->snippet = $snippet;
        $this->userForm = $userForm;
    }

    /**
     * Show listing of users
     * GET /profiles
     */
    public function getIndex()
    {
        $page = Input::get('page', 1);

        // Candidate for config item
        $perPage = 12;

        $pagiData = $this->user->byPage($page, $perPage);
        $users = Paginator::make($pagiData->items, $pagiData->totalItems, $perPage);

        return View::make('users.index', compact('users'));
    }

    /**
     * Show profile of a user
     * GET /profiles/{slug}
     */
    public function getProfile($slug)
    {
        $user = $this->user->bySlug($slug);

        if (!$user) {
            return App::abort(404);
        }

        return View::make('users.profile', compact('user'));
    }

    /**
     * Show listing of snippets of a user
     * GET /profiles/{slug}/snippets
     * @param $slug
     * @return
     */
    public function getSnippets($slug)
    {
        $page = Input::get('page', 1);

        // Candidate for config item
        $perPage = 10;

        $pagiData = $this->snippet->byAuthor($slug, $page, $perPage);
        $user = $pagiData->user;
        $snippets = Paginator::make($pagiData->items, $pagiData->totalItems, $perPage);

        return View::make('users.snippets', compact('snippets', 'user'));
    }

    /**
     * Show user's settings page
     * GET /profiles/{slug}/settings
     * @param $slug
     */
    public function getSettings($slug)
    {
        $user = Auth::user();
        return View::make('users.settings', compact('user'));
    }

    /**
     * Updates user settings
     * @param $slug
     * @return mixed
     */
    public function putSettings($slug)
    {
        $user = Auth::user();

        $result = $this->userForm->update($user, Input::all());

        if ($result) {
            return Redirect::route('user.getSettings', $slug)
                ->with('message', 'Successfully updated your settings.')
                ->with('messageType', "success");
        } else {
            return Redirect::route('user.getSettings', $slug)
                ->withInput()
                ->withErrors($this->userForm->errors());
        }
    }
}

app/views/users/index.blade.php
@extends('layouts.master')

@section('content')

    <div class="band">
        <div class="user-profiles-wrapper">

            <h1 class="heading">Members</h1>

            @if ($users->count())

                @foreach($users->chunk(4) as $usersChunked)
                    <div class="row">
                        @foreach($usersChunked as $user)
                            <div class="col-lg-3 text-center">
                                <div class="col-md-12">
                                    <img src="{{ $user->abs_photo_url }}" class="widget-author-avatar" height="65"
                                         width="65">
                                </div>

                                <div class="col-md-12">
                                    <a href="{{ route('user.getProfile', $user->slug) }}">
                                        <h4 class="name">{{ $user->full_name }}</h4>
                                    </a>

                                    <a href="{{ route('user.getSnippets', $user->slug) }}">
                                        <p>Submitted snippets: {{ $user->snippets_count }}</p>
                                    </a>
                                </div>
                            </div>
                        @endforeach
                    </div>
                @endforeach

                {{ $users->links() }}

            @else

                <h3>No site members yet.</h3>

            @endif


        </div>
    </div>

@stop

app/views/users/profile.blade.php
@extends('layouts.master')

@section('content')

  <div class="row user-profile-wrapper">
    <div class="col-md-12">

      <div class="profile-pic-con">

        <div class="row">
          <div class="col-md-3">
            <img src="{{ $user->abs_photo_url }}" id="profile-pic" height="200" width="200">
          </div>

          <div class="col-md-9 actions">

          </div>
        </div>

      </div>

      <h3>{{ e($user->full_name) }}</h3>

      <h4>About Me:</h4>

      @if($user->about_me)
        <p>{{ e($user->about_me) }}</p>
      @else
        <p>No data available.</p>
      @endif

      <h4>Links:</h4>

      <div class="links">

        @if($user->website_url || $user->twitter_url || $user->facebook_url || $user->github_url)

          @if(e($user->website_url))
            <a href="{{ e($user->website_url) }}" target="_blank">{{ e($user->website_url) }}</a>
          @endif

          @if(e($user->twitter_url))
            <a href="{{ e($user->twitter_url) }}" target="_blank">Twitter.com</a>
          @endif

          @if(e($user->facebook_url))
            <a href="{{ e($user->facebook_url) }}" target="_blank">Facebook.com</a>
          @endif

          @if(e($user->github_url))
            <a href="{{ e($user->github_url) }}" target="_blank">Github.com</a>
          @endif

        @else
          <p>No data available.</p>
        @endif

      </div>

      <br>
      <a href="{{ route('user.getSnippets', $user->slug) }}" class="btn btn-primary">View submitted snippets</a>

    </div>
  </div>

@stop

app/views/users/settings.blade.php
@extends('layouts.master')
@section('content')
    {{ Form::model($user,['route' => ['user.putSettings',$user->slug], 'method' =>'PUT', 'class'=>'form', 'role'=>'form']) }}
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    <div class='form-group @if($errors->has('username')) has-error @endif'>
                        <!-- `Username` Field -->
                        {{ Form::label('username', 'Username') }}
                        {{ Form::text('username', @$user->username, ['class'=>'form-control', 'readonly' => true]) }}
                        @if($errors->has('username'))<span
                                class="help-block">{{$errors->first('username')}}</span>@endif
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    <div class="form-group @if($errors->has('email')) has-error @endif">
                        <!-- `Email` Field -->
                        {{ Form::label('email', 'Email') }}
                        {{ Form::email('email', @$user->email, ['class'=>'form-control', 'readonly' => true]) }}
                        @if($errors->has('email'))<span class="help-block">{{$errors->first('email')}}</span>@endif
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    <div class='form-group @if($errors->has('first_name')) has-error @endif'>
                        <!-- `First name` Field -->
                        {{ Form::label('first_name', 'First name') }}
                        {{ Form::text('first_name', @$user->first_name, ['class'=>'form-control', 'placeholder' => 'Your first name']) }}
                        @if($errors->has('first_name'))<span
                                class="help-block">{{$errors->first('first_name')}}</span>@endif
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    <div class='form-group @if($errors->has('last_name')) has-error @endif'>
                        <!-- `Last name` Field -->
                        {{ Form::label('last_name', 'Last name') }}
                        {{ Form::text('last_name', @$user->last_name, ['class'=>'form-control', 'placeholder' => 'Your last name']) }}
                        @if($errors->has('last_name'))<span
                                class="help-block">{{$errors->first('last_name')}}</span>@endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    <div class='form-group @if($errors->has('twitter_url')) has-error @endif'>
                        <!-- `Twitter url` Field -->
                        {{ Form::label('twitter_url', 'Twitter url') }}
                        {{ Form::text('twitter_url', @$user->twitter_url, ['class'=>'form-control', 'placeholder' => 'Twitter URL']) }}
                        @if($errors->has('twitter_url'))<span
                                class="help-block">{{$errors->first('twitter_url')}}</span>@endif
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    <div class='form-group @if($errors->has('facebook_url')) has-error @endif'>
                        <!-- `Facebook url` Field -->
                        {{ Form::label('facebook_url', 'Facebook url') }}
                        {{ Form::text('facebook_url', @$user->facebook_url, ['class'=>'form-control', 'placeholder' => 'Facebook URL']) }}
                        @if($errors->has('facebook_url'))<span
                                class="help-block">{{$errors->first('facebook_url')}}</span>@endif
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    <div class='form-group @if($errors->has('github_url')) has-error @endif'>
                        <!-- `Github url` Field -->
                        {{ Form::label('github_url', 'Github url') }}
                        {{ Form::text('github_url', @$user->github_url, ['class'=>'form-control', 'placeholder' => 'Github URL']) }}
                        @if($errors->has('github_url'))<span
                                class="help-block">{{$errors->first('github_url')}}</span>@endif
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    <div class='form-group @if($errors->has('website_url')) has-error @endif'>
                        <!-- `Website url` Field -->
                        {{ Form::label('website_url', 'Website url') }}
                        {{ Form::text('website_url', @$user->website_url, ['class'=>'form-control', 'placeholder' => 'Website URL']) }}
                        @if($errors->has('website_url'))<span
                                class="help-block">{{$errors->first('website_url')}}</span>@endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                    <div class='form-group'>
                        <!-- `About me` Field -->
                        {{ Form::label('about_me', 'About me') }}
                        {{ Form::textarea('about_me', @$user->about_me, ['class'=>'form-control', 'placeholder' => 'Write something interesting about yourself...']) }}
                    </div>
                </div>
            </div>
        </div>
        <div class='col-md-12'>
            <!-- Form actions -->
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            <h2>Reset your password</h2>

            <div class="form-group @if($errors->has('website_url')) has-error @endif">
                {{Form::input('password', 'password', null, ['class' => 'form-control', 'placeholder' => 'New password'])}}
                @if($errors->has('password'))<span
                        class="help-block">{{$errors->first('password')}}</span>@endif
            </div>
            <div class="form-group @if($errors->has('website_url')) has-error @endif">
                {{Form::input('password', 'password_confirmation', null, ['class' => 'form-control', 'placeholder' => 'Confirm new password'])}}
                @if($errors->has('password_confirmation'))<span
                        class="help-block">{{$errors->first('password_confirmation')}}</span>@endif
            </div>
            <button type='submit' class='btn btn-primary btn-block'>Update profile</button>
        </div>
    </div>
    {{ Form::close() }}

@stop

app/views/users/snippets.blade.php
@extends('layouts.master')

@section('content')

	<h1>{{ e($user->full_name) }}'s Snippets</h1>
	{{ HTML::snippets($snippets) }}

@stop